### ISSUE TITLE
Is there any ciphering going on?

### ISSUE THREAD

**Issue by viric** [Marlinski/Rumble#15]
I cannot find any mention whether the communications go in the clear or not. Netiher a warning about text in clear, or a feature of ciphering communications.

**Comment by Marlinski** [comment]
"Public" communication, i.e. communication in public group (such as the one by default) are in clear. Communication within private group (with a little lock in the group list) are encrypted with an AES key.

**Comment by viric** [comment]
Thank you. It would be nice if this did into actual documentation or feature list.
