### ISSUE TITLE
login button on the inital screen is confusing

### ISSUE THREAD

**Issue by xoir** [Marlinski/Rumble#17]
Actually you are not providing a login by the meaning of the word "Login". To not confuse privacy-orientated people I would recommend to rename the button to "Start". I think this would make much more sense there.

![old inital screen](http://disruptedsystems.org/documentation/img/rumble-1.png) ![suggestion](http://i.imgur.com/81QDUXd.png)

The screen is the first thing people will see. Let's make sure we are not scaring them away.

**Comment by viric** [comment]
Additionally, for me the login button was completely hidden by the Android softkeyboard, and "Enter" added a newline in the login. Hiding the keyboard allowed me to see and press Login.

**Comment by Marlinski** [comment]
I close this issue related to the "login" text. I will solve the keyboard problem in a future fix

**Comment by viric** [comment]
For your information, this sounds to me like a very weird reason to close an issue: a future commit. That will break the link between the issue and the solution, and may end up with people creating duplicates of this.

**Comment by viric** [comment]
Ah sorry. Now I read better that this was only about the login text. I should have created a new issue for the keyboard problem.
