### ISSUE TITLE
Internet connecting many Rumble networks

### ISSUE THREAD

**Issue by deavmi** [Marlinski/Rumble#35]
There should be a way to get Rumble to work over the net using Tor.

**Comment by Dbof** [comment]
In my opinion...no, there should not. There is a specific use case for Rumble, and it is clearly an offline network. Making it connect online only adds complexity and reduces the overall security of the networl, as they are routed through Tor, which comes with more complications regarding privacy and security.

**Comment by PrasannaVenkadesh** [comment]
Agreed with @Dbof. Rumble is "Off the Grid".

**Comment by bcu8heq2** [comment]
Agree. Should be off-grid.

**Comment by deavmi** [comment]
Yeah. This is a good idea. But remember to encrypt the internet communications as well.

**Comment by Marlinski** [comment]
I believe this is already a feature implemented in the briar project. Though I am seduced by the Idea of using TOR and hidden services as a way to bridge people,  Rumble does not intend to work over the Internet at the time.
