### ISSUE TITLE
photo is only send when text is added

### ISSUE THREAD

**Issue by SimJoSt** [Marlinski/Rumble#44]
If you try to post a photo, it will not be send and no error message is displayed.
Only if additionally text is added to the post, the photo will be send.

**Comment by Marlinski** [comment]
would you prefer I add a notification or being able to send a picture without texte ?

**Comment by SimJoSt** [comment]
Good question.
I believe allowing to post photos without text is the more preferable option. I can't think of a reason to disallow it.

**Comment by Marlinski** [comment]
Since every status is passed around, you cannot easily trace back the context/origin of a photo. I guess I thought it would be better to force some text, but I agree the implementation was lacking at least a notification :) I'll fix it

**Comment by SimJoSt** [comment]
Perfect :)
But just so I understand: How is a photo post any different from a text post regarding it's difficult to trace origin?
