### ISSUE TITLE
Android Studio import/sync error - default configuration not found

### ISSUE THREAD

**Issue by SimJoSt** [Marlinski/Rumble#45]
While adding the Rumble project to Android Studio, it tries to sync the project and comes up with this error:

> Gradle 'Rumble' project refesh failed
> Error: Configuration with name 'default' not found.

full log: https://gist.github.com/SimJoSt/a6130cd03468edc6e2fc12027060ce8c

**Comment by Marlinski** [comment]
did you properly pull the submodule ? 
it can be done either by cloning rumble recursively or by entering git submodule update --init

**Comment by SimJoSt** [comment]
Of course I didn't^^
Thanks for pointing that out and sorry for this waste of time...
