### ISSUE TITLE
Hardware compatibility in f-droid

### ISSUE THREAD

**Issue by taranarmo** [Marlinski/Rumble#6]
![screenshot_20151215-190924](https://cloud.githubusercontent.com/assets/11619234/11816104/f2aa5762-a35f-11e5-9ad9-c9a8c3bb706c.png)
Application requires camera, I suppose, which my tablet (Nexus 7, 2nd gen) has, but  f-droid indicates that app is not compatible with.
BTW application works fine.

**Comment by Marlinski** [comment]
The camera is used to scan a group invitation (in the form of a QRCode).
I suppose I can safely remove this requirement, I'll do some check, thanks for letting me know.

**Comment by PrasannaVenkadesh** [comment]
I installed Rumble through Play Store, the app lists my device as not compatible in f-droid. I am not able to find which permission makes my device incompatible in f-droid.

**Comment by taranarmo** [comment]
Today I've got upgrade from f-droid and saw that rumble requires camera flash, not only camera. So, I think it is safe to remove that requirement.
