### ISSUE TITLE
Input field in the Chat area is too low.

### ISSUE THREAD

**Issue by vanitasvitae** [Marlinski/Rumble#9]
Hi
In my Nexus 5, the Text input field is shifted too low. i can barely click it.

**Comment by aleksen** [comment]
I think this is a duplicate of https://github.com/Marlinski/Rumble/issues/5

**Comment by deavmi** [comment]
My friend is also experiencing this.

**Comment by Marlinski** [comment]
duplicate of #5 which should be fixed now.
